### ISSUE TITLE
not sync between image and name of the pokemon

### ISSUE THREAD

**Issue by ryananjasmara** [ryananjasmara/pokemon-ruphirald#26]
#### Describe The Bug
not sync between pokemons image and pokemons name.

#### To Reproduce
only occured on load more pokemons.

#### Expected Behavior
pokemons image and pokemons name sync.

#### Screenshots
![image](https://user-images.githubusercontent.com/57338415/95023821-53cb3c80-06a9-11eb-9608-cde8ea1cd514.png)

**Comment by dipanshubhola1009** [comment]
I m interested. assign this to me

**Comment by ryananjasmara** [comment]
assigned, anyway what's your solution for this @dipanshubhola1009 ?

**Comment by dipanshubhola1009** [comment]
I m looking for the source they are coming. as soon as I got the solution I will generate PR

**Comment by dipanshubhola1009** [comment]
I have checked your Code i did not found any issue in that. but Image your displaying from API is wrong.

**Comment by ryananjasmara** [comment]
soo its from the API response huh?, well that make sense. anyway thanks for looking this, ill merge ur PR for credit to debug this.
