### ISSUE TITLE
shiny pokemon image is missing? 

### ISSUE THREAD

**Issue by ryananjasmara** [ryananjasmara/pokemon-ruphirald#27]
#### Describe The Bug
shiny pokemon image is missing.

#### To Reproduce
open pokemon detail, in that page there is carousel which show pokemon images, but somehow shiny images is missing. I think the response from the API changed.
API : https://pokeapi.co/

#### Expected Behavior
shiny images shown as well.

#### Screenshots
shiny image not shown
![image](https://user-images.githubusercontent.com/57338415/95024034-c12b9d00-06aa-11eb-9c56-a9bc55e80b8e.png)

normal image is shown
![image](https://user-images.githubusercontent.com/57338415/95024050-e6b8a680-06aa-11eb-85eb-443126de526c.png)

**Comment by SebaCaste** [comment]
I like this one! can you assign it to me?

**Comment by ryananjasmara** [comment]
sure, please take a look at API response @SebaCaste
